# Generated by Django 3.2.11 on 2023-02-01 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20230201_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 1, 15, 44, 15, 42906)),
        ),
        migrations.AlterField(
            model_name='messagebox',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 1, 15, 44, 15, 42906)),
        ),
    ]
